FinalProject/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/master', function () {
    return view('layouts.master');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('news', 'NewsController');
Route::resource('categories', 'CategoriesController');

FinalProject/app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = 'news';
}

FinalProject/app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use File;
use App\News;
use App\Categories;
use App\User;
use Auth;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct() {
        $this->middleware('auth')->except(['index', 'show']);
    }

    public function create()
    {
        $categoriesss = Categories::all();
        return view('pages.news.create', compact('categoriesss'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $request -> validate([
            'title' => 'required',
            'body' => 'required',
            'categories_id' => 'required'
        ]);

        $image =  $request->poster;
        $name_img = time(). " - ". $image->getClientOriginalName();

        $news = new News;
        $news->title = $request['title'];
        $news->sub_title = $request['sub_title'];
        $news->body = $request['body'];
        $news->poster = $name_img;
        $news->users_id = Auth::id();
        $news->categories_id = Auth::id();
        
        $news->save();
        $image->move('img', $name_img);

        return redirect('/news')->with('success', 'News was posted successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $newss = News::all();
        return view('pages.news.index', compact('newss'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function show($id)
    {
        $news = News::find($id);
        $categoriessss = Categories::find($id);
        $users = User::find($id);
        return view('pages.news.show')->with(compact('news', $news))->with(compact('categoriessss', $categoriessss))->with(compact('users', $users));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = News::find($id);
        $categoriesss = Categories::all();
        $users = User::find($id);
        return view('pages.news.edit')->with(compact('news', $news))->with(compact('categoriesss', $categoriesss))->with(compact('users', $users));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request -> validate([
            'title' => 'required',
            'body' => 'required',
            'categories_id' => 'required'
        ]);

        $news = News::findorfail($id);
        if ($request->has('poster')) {
            $path="img/";
            File::delete($path. $news->poster);
            $image =  $request->poster;
            $new_img = time(). " - ". $image->getClientOriginalName();
            $image->move('img', $new_img);
            $update = News::where('id', $id)->update([
                'title' => $request['title'],
                'sub_title' => $request['sub_title'],
                'body' => $request['body'],
                'poster' => $new_img,
                'categories_id' => Auth::id()
            ]);
        }
        else {
            $update = News::where('id', $id)->update([
                'title' => $request['title'],
                'sub_title' => $request['sub_title'],
                'body' => $request['body'],
                'categories_id' => Auth::id()
            ]);
        }

        return redirect('/news')->with('success', 'Changes saved!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $destroy = News::findorfail($id);
        $destroy->delete();
        $path = "img/";
        File::delete($path. $destroy->poster);
        return redirect('/news')->with('success', 'News was successfully deleted!');
    }
}

FinalProject/resources/views/pages/news/create.blade.php
@extends('layouts.master')

@section('content')
        <div class="ml-3 mt-3 mr-3">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Write a News</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/news" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="titleInput">Title</label>
                    <input type="text" class="form-control" name="title" value="{{ old('title', '') }}" id="titleInput" placeholder="Title of the news goes here...">
                    @error('title')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="sub_titleInput">Sub Title</label>
                    <input type="text" class="form-control" name="sub_title" value="{{ old('sub_title', '') }}" id="sub_titleInput" placeholder="Sub Title of the news goes here...">
                    @error('sub_title')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="bodyInput">Body</label>
                    <input type="text" class="form-control" name="body" id="bodyInput" value="{{ old('body', '') }}" placeholder="News goes here...">
                    @error('body')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="categoriesInput">Category</label><br>
                    <select name="categories_id" id="categoriesInput" class="form-control">
                      <option value="">-</option>
                      @foreach ($categoriesss as $value) 
                        <option value="{{$value->id}}">{{$value->category_name}}</option>
                      @endforeach
                    </select>
                    @error('categories_id')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="posterInput">Poster</label>
                    <input type="file" class="form-control" name="poster" value="{{ old('poster', '') }}" id="posterInput" placeholder="Upload a Poster">
                    @error('poster')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
@endsection

FinalProject/resources/views/pages/news/edit.blade.php
@extends('layouts.master')

@section('content')
        <div class="ml-3 mt-3 mr-3">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit News</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="/news/{{$news->id}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="card-body">
                  <div class="form-group">
                    <label for="titleInput">Title</label>
                    <input type="text" class="form-control" name="title" value="{{ old('title', $news->title) }}" id="titleInput" placeholder="Title of the news goes here...">
                    @error('title')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="sub_titleInput">Sub Title</label>
                    <input type="text" class="form-control" name="sub_title" value="{{ old('sub_title', $news->sub_title) }}" id="sub_titleInput" placeholder="Sub Title of the news goes here...">
                    @error('sub_title')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="bodyInput">Body</label>
                    <input type="text" class="form-control" name="body" id="bodyInput" value="{{ old('body', $news->body) }}" placeholder="News goes here...">
                    @error('body')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="categoriesInput">Category</label><br>
                    <select name="categories_id" id="categoriesInput" class="form-control">
                      <option value="">-</option>
                      @foreach ($categoriesss as $value) 
                        <option value="{{$value->id}}">{{$value->category_name}}</option>
                      @endforeach
                    </select>
                    @error('categories_id')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="posterInput">Poster</label>
                    <input type="file" class="form-control" name="poster" value="{{ old('poster', $news->poster) }}" id="posterInput" placeholder="Upload a Poster">
                    @error('poster')
                      <div class='alert alert-danger'>{{ $message }}</div>
                    @enderror
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
@endsection

FinalProject/resources/views/pages/news/index.blade.php
@extends('layouts.master')

@section('content')
    @forelse($newss as $value)
        <div class="card" style="width: 90rem">
            <div class="card-body">
                <div class="card" style="width: 88rem">
                    <img src="{{asset('img/'.$value->poster)}}"  height="500px" class="card-img-top" alt="...">
                    <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif
                        <h1 class="card-title">
                            <strong><a href="/news/{{$value->id}}">
                                {{$value->title}}
                            </a></strong>
                        </h1><br>
                        <p class="card-text">{{$value->created_at}}</p>
                        <form action="{{route('news.destroy', ['news' => $value->id])}}" method="POST">
                            <a href="/news/{{$value->id}}/edit" class="btn btn-success">Edit</a>
                            @csrf
                            @method('DELETE')
                            <input type="submit" value='Delete' class="btn btn-danger">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    @empty
        <h1 align="center">No News Available</h1>
    @endforelse
@endsection

FinalProject/resources/views/pages/news/show.blade.php
@extends('layouts.master')

@section('content')
<div class="ml-3 mt-3 mr-3">
    <div class="card">
        <div class="ml-2 mr-2">
            <h1>{{$news->title}}</h1>
            <h5>{{$news->sub_title}}</h5>
            <h7>Posted on: {{$news->created_at}}</h7>
            <img src="{{asset('img/'.$news->poster)}}" height="500px" class="card-img-top" alt="...">
            <p>{{$news->body}}</p>
        </div>
    </div>
</div>
@endsection